### ISSUE TITLE
A variation on your theme

### ISSUE THREAD

**Issue by quentinsf** [edent/BMW-i-Remote#1]
Hi Terence - 

I've made quite a few changes to your original - it's sufficiently different that you may want to completely ignore it, but I can do a pull request if wanted!  

Basically, I've pulled your original tweeting code out into bmwtweet.py and made a more generic 'bmw' module. 

You can do things like:

```
import bmw
c = bmw.ConnectedDrive()
print c.call('/user/vehicles/')
```

It uses the 'requests' module, so you need to pip install that if you don't already have it.

Anyway, it's at https://github.com/quentinsf/BMW-i-Remote if you're interested.  More to come soon.

Thanks again!
Quentin

**Comment by edent** [comment]
Your Python-fu is mightier than mine! Go ahead with a PR :-)
