### ISSUE TITLE
BMW server API rate limit

### ISSUE THREAD

**Issue by thickey256** [edent/BMW-i-Remote#13]
I have been playing about with this and my new i3 which I got last week.  I prefer PHP rather than python so I went with that, I found the curl documentation here was invaluable in helping me to get things working.  I have written a script that posts any changes in status to a slack channel rather than twitter.

Everything is working happily and I have a cron job running every 5 minutes to grab the status, if the timestamp has changed (or if the status has changed if it's charging) then it posts a new message to slack. yay!
![screen shot 2016-07-06 at 14 09 01](https://cloud.githubusercontent.com/assets/108245/16619123/b1ec471a-4384-11e6-864c-0527fc7fc995.png)

While I was looking at this last night I noticed that the status doesn't change unless something physically is different with the car.. totally makes sense. What doesn't make sense to me from a technical perspective is that while the vehicle is in motion nothing seems to change. After a drive home from work the updatedReason changed to VEHICLE_MOVING and kept the same timestamp until I got home and parked.  I guess the theory behind this is that people aren't going to be using the iRemote on their phones while driving the car.

I did however notice that when charging my i3 the timestamp would change upon every request (I hit refresh a bunch of times and even after a second or two it changed). I'm not sure that up to the second information is necessary and the implications on servers and mobile data would make that a silly thing to me for the car to be doing.. but there ya go.  perhaps there is some backend tasks going on where the server calculates what the battery % increase should be based on the charging speed etc and so isn't actually talking to the car directly.

What's my point.. oh yes..  based on the fact that I appear to be able to make new requests every second what do people think is a sensible frequency for requests to be made.  I was thinking of going down to 1 every 60 seconds. I'm not sure how easy it would be for BMW to detect/block access for a homemade client.. but I don't want to hammer something and then get myself or everyone blocked..  What does everyone/anyone think?

Also would a PR with the php->slack code be of use to anyone.. would it be better as a separate repo?

**Comment by edent** [comment]
I noticed that - updates are only really when parked.

> but I don't want to hammer something and then get myself or everyone blocked.. What does everyone/anyone think?

I do it hourly and haven't run into any issues.  BMW will be paying (a small amount) for the mobile data use, so best not to abuse it.

> Also would a PR with the php->slack code be of use to anyone.. would it be better as a separate repo?

I'm happy to have it on here - but I won't be offended if you want it under your own control :-)

**Comment by nloui** [comment]
@thickey256 I'd hack away at a PHP version with you 👍

**Comment by thickey256** [comment]
@nloui This is what I have come up with so far. https://github.com/thickey256/iRemote-PHP

**Comment by stefferber** [comment]
You have to understand how gas/diesel cars typically dealing while turned off:
As you turn off a car it will stay in a semi-active mode for some time - just a few minutes. This is called "Nachlauf" in German engineering and I would translate this to "coastdown" in English. After that the car is shutdown to protect the battery ("Klemme 15"). 

For electric vehicles this is very different as during charging the car is still active while not driving. Hence, no-driving and non-charging status you should also be careful waking up your car too often.
