### ISSUE TITLE
Opening the trunk only?

### ISSUE THREAD

**Issue by stefferber** [edent/BMW-i-Remote#16]
Hi,
we played with the API and we tried to unlock the trunk ONLY. The remote key has that capability but we could not find the API call. As the vehicle status distinguishes all doors, trunk, and hood:

```
{
  "vehicleStatus": {
[...]
    "updateReason": "DOOR_STATE_CHANGED",
[...]
    "doorDriverFront": "CLOSED",
    "doorDriverRear": "CLOSED",
    "doorPassengerFront": "CLOSED",
    "doorPassengerRear": "CLOSED",
    "windowDriverFront": "CLOSED",
    "windowDriverRear": "CLOSED",
    "windowPassengerFront": "CLOSED",
    "windowPassengerRear": "CLOSED",
    "trunk": "CLOSED",
    "rearWindow": "INVALID",
    "hood": "CLOSED",
    "doorLockState": "SELECTIVE_LOCKED",
   [...]
```

why not have an API call for it, too. Any idea?
@stefferber

**Comment by SleeplessAnnoyedNerd** [comment]
Hi,

b/c BMW hasn't implemented it. At least mobile application doesn't support it so I'm pretty sure there is no API call. Not sure why, b/c (un)locking of car is possible though.

Kind regards,
Dietmar
