### ISSUE TITLE
Latency Experience?

### ISSUE THREAD

**Issue by stefferber** [edent/BMW-i-Remote#17]
Hi,
we are experiencing latency time of 25-60s for an API call and the iRemote App using:
- https://b2vapi.bmwgroup.com 
- Vodafone 4G with iRemote App on iPhone 6
- Car and Phone located in Stuttgart

Looks like we need about
10s to connect with the BMW server
20-50s to wake up the car

What is your experience?

@stefferber

**Comment by SleeplessAnnoyedNerd** [comment]
Hi,

yes, API is sometimes (mostly) slow and sometimes not. (https://b2vapi.bmwgroup.com/webapi). Car located in Austria.

Kind regards,
Dietmar
