### ISSUE TITLE
SSL certificate pinning in new clients?

### ISSUE THREAD

**Issue by mnbf9rca** [edent/BMW-i-Remote#19]
Using IOS I am trying to capture the traffic using Charles proxy. Usually this works for me - but the BMW apps all refuse to connect. I get the same sort of error as when a browser is using HSTS I.e. the session terminates before completing handshake. Has anyone got traffic interception working recently?

**Comment by mnbf9rca** [comment]
ok so i managed to get a key + secret. But they are apparently not valid for the scopes remote_services or vehicle_data

**Comment by mnbf9rca** [comment]
ok keys obtained through other methods.

**Comment by mkormendy** [comment]
> ok keys obtained through other methods.

Which other methods? I'm having this same issue.
