### ISSUE TITLE
Can I use these APIs to interact with BMW non-electric cars?

### ISSUE THREAD

**Issue by fpemud** [edent/BMW-i-Remote#21]
I know all recent models of BMW cars support ConnectedDrive.
But can I use (a subset of) these APIs to interact with BMW non-electric cars, such as BMW X1, BMW X3?

**Comment by edent** [comment]
Try it and let us know.

**Comment by ryanbuckner** [comment]
I was able to use the APIs successfully on my 2015 535 to lock door, flash lights, honk horn, and start the climate control. I'm having issues with Get Vehicle Status and door_unlock

**Comment by mnbf9rca** [comment]
@fpemud  @ryanbuckner see https://github.com/edent/BMW-i-Remote/issues/20 - it works, just that location services don't and you don't get back the same response object.
