### ISSUE TITLE
Howto for dummy ?

### ISSUE THREAD

**Issue by donballes** [edent/BMW-i-Remote#24]
Hi, can anybody give me a step by step guide... sorry 
I´m not so deep into coding... and i have only the iPhone app.
Is there a way to get the password/secret of connected drive without an android phone?

Thanks

**Comment by edent** [comment]
Hi Don,

If you're not a coder, you may find it easier to use BMW's official IFTTT services - see https://ifttt.com/bmwlabs

Hope that's helpful.

**Comment by SleeplessAnnoyedNerd** [comment]
There is just one catch... BMW Labs is -- to my knowledge -- currently unfortunately not available for all regions :(
