### ISSUE TITLE
Minor typo in documentation for Send POI: snedpoi => sendpoi

### ISSUE THREAD

**Issue by SleeplessAnnoyedNerd** [edent/BMW-i-Remote#25]
Hi,

a really minor typo: `POST /webapi/v1/user/vehicles/:VIN/snedpoi`
should be: `POST /webapi/v1/user/vehicles/:VIN/sendpoi`

Thanks,
Dietmar

**Comment by edent** [comment]
Good spot! Please sned a pull request ☺️
