### ISSUE TITLE
Can the i3 APIs be used as is with the 2017 i3s?

### ISSUE THREAD

**Issue by rickengle** [edent/BMW-i-Remote#31]
Hi, my lease is up on my 2015 i3 REX and looking at the 2017 REX.   Has anyone found out if the same APIs work including the master key and the same JSON response strings?

Thanks!
 Rick

**Comment by mchenetz** [comment]
I use with my 2017 i3

**Comment by rickengle** [comment]
That's fantastic to hear.  I ordered my 2017 i3 REX so its super that my APIs will still work!

  Rick
