### ISSUE TITLE
Unlock Command missing secretKnowledge

### ISSUE THREAD

**Issue by nosrak113** [edent/BMW-i-Remote#33]
In order to call the DOOR_UNLOCK command, it seem the api is also looking for a secretKnowledge field. 
```{"error":{"code":500,"description":"(SmartPhoneUtil-A-2013) Action is forbidden. secretKnowledge is missing but required!"}}```

This secret is the answer to the security question on the users account. I can't seem to find where to put it in the request. Ive tried in the body and headers under "secretKnowledge", but no luck.

Has anyone gotten this to work?

**Comment by nosrak113** [comment]
seems the request needs to include 
```'bmwSkAnswer': MY_BMW_SECRET```

**Comment by edent** [comment]
Could you send a PR to change the README please?
