### ISSUE TITLE
General API comments

### ISSUE THREAD

**Issue by rickengle** [edent/BMW-i-Remote#4]
Hi all, great job on the APIs documentation.   I used the Python to start off testing along with cURL but then once I got up to speed I built C# code on Windows to access the BMW service calls.   I have been using Charles for URL sniffing which has been very helpful.
I noticed a few things.
In your article where you showed the response JSON from a vehicle status, there are more items that can be retrieved if the car is charging which would be good to include.
I found that the chargingTimeRemaining value added to the current time doesn't often match up with the estimated time to complete charging shown on the i3 dash.   I wonder why.

When retrieving the vehicle status I was wondering why once I got status it didn't seem to change unless I restarted my app.  I guessed that it was a caching issue and although I later figured out how to fix that through code I adopted the same technique BMW did to force each request to be new by appending the time stamp onto the request like this:
https://b2vapi.bmwgroup.us/webapi/v1/user/vehicles/MYVIN/status?deviceTime=2015-12-30T10%3A06%3A13

I included a polling cycle for command executions to look for DELIVERED, PENDING and then exit the wait if an EXECUTED or TIMED_OUT message is returned.

Something funny about door lock.   It works fine but I noticed that it doesn't turn on the car alarm.   If you look outside of your car when doing a DOORLOCK using the API, the doors lock but then the light under the rear-view mirror is not flashing.   If I then press the lock button on my remote, it takes it a step further and turns on the alarm.

I noticed a status from door lock that was odd.  I have seen selective_locked but I can't tell what that means.  I have been trying to create alternative human readable messages to translate BMW messages but don't know what that means.

I tried to create a DOOR_UNLOCK command but that failed.   I think why that is could be because it is not enabled by the car.   In the vehicles information object retrieved it shows this:
"doorUnlock": "NOT_SUPPORTED".   I assume that if an action says NOT-SUPPORTED then the API cannot control it.   Does that sound right?

Has anyone found a way to generate the app's secret token based on using the user's ID and password?  That would be super helpful.

Thanks,
  Rick

**Comment by edent** [comment]
Hi Rick - thanks for your comments.

> In your article where you showed the response JSON from a vehicle status, there are more items that can be retrieved if the car is charging which would be good to include.

Good spot! Can you please add them into the main documentation?  You can edit the doc at https://github.com/edent/BMW-i-Remote/edit/master/README.md

> I adopted the same technique BMW did to force each request to be new by appending the time stamp onto the request

Interesting. I didn't bother including that because I wasn't seeing any cached data. I wonder where the cache is occurring - at BMW's end or somewhere else on the network?

> Something funny about door lock. It works fine but I noticed that it doesn't turn on the car alarm.
> and
> I tried to create a DOOR_UNLOCK command but that failed. I think why that is could be because it is not enabled by the car.

I wonder if that's a region specific thing? I know that the UK models don't let you sound the horn via the API. Which region are you in?

> Has anyone found a way to generate the app's secret token based on using the user's ID and password? That would be super helpful.

Not yet :-)

Thanks!

**Comment by rickengle** [comment]
I'm in the US region.  Oh by the way that's a neat tidbit too.  When I first started out I was using the UK's URL from your article and that worked for me to authenticate and get the Bearer ID but then stumped me since I got authentication errors for everything else, when I used the US URL like my iPhone iRemote app was using then it worked.
Here is what I have in my vehicle info section:
        "countryCode": "V2-US",
        "egoVehiclePath": "I01",
        "asymEncryptionMethod": "RSA-2048",
        "remote360packageEncryption": "ZIP",
        "vehicleFinder": "ACTIVATED",
        "remote360": "NOT_SUPPORTED",
        "hornBlow": "ACTIVATED",
        "lightFlash": "ACTIVATED",
        "doorLock": "ACTIVATED",
        "doorUnlock": "NOT_SUPPORTED",
        "climateControl": "NOT_SUPPORTED",
        "climateNow": "ACTIVATED",
        "chargingControl": "WEEKLY_PLANNER",
        "chargeNow": "NOT_SUPPORTED",
        "sendPoi": "ACTIVATED",
        "rangeMap": "RANGE_POLYGON",
        "lastDestinations": "SUPPORTED",
        "intermodalRouting": "AVAILABLE",
        "climateFunction": "AIRCONDITIONING",
        "onlineSearchMode": "MAP",
        "smartSolution": "NOT_SUPPORTED",
        "supportedChargingModes": ["AC_LOW", "AC_HIGH", "DC"],
        "lscType": "I_LSC_IMM"

When you check on your side for lightFlash, does that show as NOT-SUPPORTED?

Regarding caching, it could be that the Python http (requests?) library already takes care of not caching so it doesn't have the issue that the Windows HttpClient class has.

What kind of file format is .md?   I need to find an editor for it.
Oh in the docs you probably don't have an example for the output from /webapi/v1/user/vehicles/ do you?  Its not in your original article.

Thanks.
 Rick

**Comment by rickengle** [comment]
Terence, did you see the question above?  I'm curious what the output was from a UK i3 perspective on what shows up as NOT_SUPPORTED in the vehicle info response.

**Comment by edent** [comment]
Sorry for the delayed response.

> Regarding caching, it could be that the Python http (requests?) library already takes care of not caching so it doesn't have the issue that the Windows HttpClient class has.

Ah! That's probably it.

> What kind of file format is .md? I need to find an editor for it.

`.md` is [MarkDown](https://en.wikipedia.org/wiki/Markdown) you should be able to edit it with notepad.  I don't use Windows, but I'm sure there's some freeware which will help with the formatting.

> Oh in the docs you probably don't have an example for the output from /webapi/v1/user/vehicles/ do you? Its not in your original article.

I don't think so - do feel free to add it.

**Comment by ryanbuckner** [comment]
I'm in the US. Here's my status for doorUnlock

   doorUnlock  :  SECRET_KNOWLEDGE
